### ISSUE TITLE
attribute 'no_cs' not existing with python 3.5

### ISSUE THREAD

**Issue by tgd1975** [doceme/py-spidev#68]
Hi, 

this code snipped works with python 2.7:

```
import spidev

spi = spidev.SpiDev()
spi.open(0, 1)
spi.max_speed_hz = 500000
spi.no_cs = True
print(spi.xfer2([0xFF]))
spi.close()
```
when beeing executed with python 3.5, it yields the error "AttributeError: 'SpiDev' object has no attribute '**no_cs**'".

Python 2.7.13
Python 3.5.3
Raspberry Pi 3, Raspbian Strech , kernel 4.9.59+

tobias

**Comment by fabianWhoknows** [comment]
Same issue here with Python 3.4.2 ...

**Comment by moizgillani** [comment]
Have you found any solution for this?

**Comment by karenakhumyan** [comment]
use `spi.mode = 1` instead
